### ISSUE TITLE
Find a new maintainer for the project

### ISSUE THREAD

**Issue by videlalvaro** [php-amqplib/Thumper#28]
As you might know, I'm leaving the company that makes RabbitMQ https://groups.google.com/forum/#!topic/rabbitmq-users/-byffkRnI2w, so I will have even less time to take care of this project. Therefore I'm opening this issue so the community helps with finding a new maintainer(s) for the project.

While I would like to have a stronger say on who should take care of the project, I would ask contributors and users to propose who you think would be a great candidate. Please comment on this issue and help find that person.

Besides from knowing PHP, you must be very familiar with at least these concepts: http://www.rabbitmq.com/tutorials/amqp-concepts.html

**Comment by tyx** [comment]
It does not help the thread but I would like to thank you for all you did for the PHP community on the RabbitMQ topic !

**Comment by videlalvaro** [comment]
@tyx thanks!

**Comment by olleolleolle** [comment]
Just keeping the love streaming: THANK YOU for all your hard work explaining this thing to people. <3 <3 <3

**Comment by Swader** [comment]
If you don't find anyone passionate and dedicated enough to one-man it, we at SitePoint's PHP channel wouldn't mind taking over (see [this](https://github.com/sitepoint/awesome-symfony/) and [here](https://github.com/sitepoint/rtdsphinx-php) for examples of what we intend to maintain). While individually we're probably underqualified as RabbitMQ users are rare in our circles (at the moment), I'm sure that as a collective, we could do the repo justice, especially by doing writeups about it and attracting outside contributors and amqp experts that way.

Good luck!

**Comment by postalservice14** [comment]
Did you want to make this apart of the [php-amqplib](https://github.com/php-amqplib) Github Organization as well?

**Comment by postalservice14** [comment]
Also, I wouldn't mind helping out with this package as well...

**Comment by videlalvaro** [comment]
Makes sense
